"use client";
import Link from "next/link";
import { useState } from "react";
import { useStreamStock } from "@/lib/useStreamStock";
import { compact, money, priceFor } from "@/lib/market";

export default function HomePage() {
  const app = useStreamStock();
  const [q, setQ] = useState("");
  const gainers = [...app.state.streamers].sort((a,b)=>b.dayChange-a.dayChange).slice(0,5);
  const losers = [...app.state.streamers].sort((a,b)=>a.dayChange-b.dayChange).slice(0,5);
  const filtered = app.state.streamers.filter(s => `${s.name} ${s.ticker}`.toLowerCase().includes(q.toLowerCase()));
  const Row = ({s}:{s:any}) => <Link className="market-row clickable-row" href={`/streamer/${s.ticker}`}><div><strong>{s.name}</strong><p className="muted">{s.ticker} · {compact(s.followers)} followers · {compact(s.avgViewers)} avg viewers</p></div><div style={{textAlign:"right"}}><strong>{money(priceFor(s))}</strong><p className={s.dayChange>=0?"gain":"loss"}>{s.dayChange>=0?"+":""}{s.dayChange}%</p></div></Link>;
  return <>
    <section className="hero compact-hero"><div className="hero-copy"><div className="pill">Fantasy markets for Twitch culture</div><h1>Trade streamer momentum.</h1><p>Prices are built from followers, average viewers, stream hours, recent growth, and market demand. The serious finance look, but chat is absolutely not serious.</p><div className="hero-actions"><Link className="primary-btn" href="#market">View market</Link><Link className="secondary-btn" href="/portfolio">Portfolio</Link></div></div><div className="hero-card glass-card"><div className="hero-card-top"><span>Buying power</span><strong>{money(app.state.cash)}</strong></div><div className="ticker-tape">{gainers.slice(0,4).map(s=><div className="tape-item" key={s.ticker}><strong>{s.ticker}</strong><span>{money(priceFor(s))}</span><span className={s.dayChange>=0?"gain":"loss"}>{s.dayChange>=0?"+":""}{s.dayChange}%</span></div>)}</div><p className="muted">Streamer stocks. Fake coins. Real-looking chaos.</p></div></section>
    <section className="stats-row compact-stats"><article className="stat-card"><span>Buying Power</span><strong>{money(app.state.cash)}</strong></article><article className="stat-card"><span>Total Account Value</span><strong>{money(app.accountValue)}</strong></article><article className="stat-card"><span>Total Return</span><strong className={app.totalReturn>=0?"gain":"loss"}>{app.totalReturn>=0?"+":""}{money(app.totalReturn)}</strong></article><article className="stat-card"><span>Open Orders</span><strong>{app.state.orders.length}</strong></article></section>
    <section className="section-grid" id="market"><div className="section-heading"><p className="eyebrow">Market pulse</p><h2>Top gainers and losers</h2><p>Click any streamer to open the chart and trade page.</p></div><div className="market-lists"><article className="panel"><div className="panel-head"><h3>Top Gainers</h3><span className="gain">Today</span></div><div className="list-stack">{gainers.map(s=><Row key={s.ticker} s={s}/>)}</div></article><article className="panel"><div className="panel-head"><h3>Top Losers</h3><span className="loss">Today</span></div><div className="list-stack">{losers.map(s=><Row key={s.ticker} s={s}/>)}</div></article></div></section>
    <section className="panel full"><div className="panel-head wrap"><div><h3>Streamer Market</h3><p className="muted">Search the board. Open a streamer to chart and trade.</p></div><input className="search" value={q} onChange={e=>setQ(e.target.value)} type="search" placeholder="Search streamer or ticker..." /></div><div className="table-wrap"><table><thead><tr><th>Streamer</th><th>Ticker</th><th>Followers</th><th>Avg Viewers</th><th>Price</th><th>Day</th><th></th></tr></thead><tbody>{filtered.map(s=><tr key={s.ticker}><td><strong>{s.name}</strong></td><td><span className="ticker-badge">{s.ticker}</span></td><td>{compact(s.followers)}</td><td>{compact(s.avgViewers)}</td><td>{money(priceFor(s))}</td><td className={s.dayChange>=0?"gain":"loss"}>{s.dayChange>=0?"+":""}{s.dayChange}%</td><td><Link className="row-btn" href={`/streamer/${s.ticker}`}>Open</Link></td></tr>)}</tbody></table></div></section>
  </>;
}
